/**
 * Code-review rendering — pure helpers (no I/O). Turns the AI's structured
 * findings into counts, a verdict summary, and a sectioned artifact snapshot
 * (the KB-readable projection) while keeping the structured findings in
 * content.data for the UI.
 */
import type { ArtifactContent } from "@/lib/artifacts/content";

export type Severity = "blocking" | "suggestion" | "nitpick";
export type Dimension = "bug" | "security" | "performance" | "standards" | "tests";

export type CodeFinding = {
  file: string;
  line: number | null;
  severity: Severity;
  dimension: Dimension;
  message: string;
  suggestion?: string;
};

export type CodeReviewResult = {
  verdict: "approve" | "request_changes";
  summary: string;
  findings: CodeFinding[];
};

export function countsBySeverity(findings: CodeFinding[]): Record<Severity, number> {
  return findings.reduce<Record<Severity, number>>(
    (acc, f) => {
      acc[f.severity] += 1;
      return acc;
    },
    { blocking: 0, suggestion: 0, nitpick: 0 }
  );
}

function findingsMarkdown(findings: CodeFinding[]): string {
  if (findings.length === 0) return "No issues found.";
  return [
    `| Severity | Dimension | Location | Issue |`,
    `|---|---|---|---|`,
    ...findings.map(
      (f) =>
        `| ${f.severity} | ${f.dimension} | ${f.file}${f.line ? `:${f.line}` : ""} | ${f.message.replace(/\n/g, " ")} |`
    ),
  ].join("\n");
}

export function buildReviewContent(
  result: CodeReviewResult,
  prNumber: number
): ArtifactContent {
  const c = countsBySeverity(result.findings);
  const verdict = [
    `**Verdict: ${result.verdict === "approve" ? "Approve" : "Request changes"}**`,
    ``,
    `Blocking: ${c.blocking} · Suggestions: ${c.suggestion} · Nitpicks: ${c.nitpick}`,
    ``,
    result.summary,
  ].join("\n");

  return {
    sections: [
      { key: "verdict", title: "Verdict", body: verdict },
      { key: "findings", title: "Findings", body: findingsMarkdown(result.findings) },
    ],
    data: { prNumber, verdict: result.verdict, summary: result.summary, findings: result.findings },
  };
}

export type ReviewPayload = {
  summaryBody: string;
  event: "COMMENT" | "REQUEST_CHANGES";
  inlineComments: { path: string; line: number; body: string }[];
};

/**
 * Build the payload for a GitHub PR Review (POST /pulls/{n}/reviews).
 * Findings with a line number become inline comments; line-less findings
 * are folded into the summary body so nothing is lost.
 * We never submit APPROVE — the AI informs the human reviewer, not replaces them.
 */
export function buildReviewPayload(result: CodeReviewResult, prNumber: number): ReviewPayload {
  const c = countsBySeverity(result.findings);
  const event: ReviewPayload["event"] =
    result.verdict === "approve" ? "COMMENT" : "REQUEST_CHANGES";

  const header = [
    `### 🤖 ABC Code Review — PR #${prNumber}`,
    `**${result.verdict === "approve" ? "✅ Looks good" : "🔧 Request changes"}** · Blocking ${c.blocking} · Suggestions ${c.suggestion} · Nitpicks ${c.nitpick}`,
    ``,
    result.summary,
  ];

  const unanchored = result.findings.filter((f) => f.line === null);
  if (unanchored.length > 0) {
    header.push("", "**Additional findings (no line anchor):**");
    for (const f of unanchored) {
      header.push(
        `- **[${f.severity}]** ${f.dimension} — \`${f.file}\`: ${f.message.replace(/\n/g, " ")}${f.suggestion ? ` _(fix: ${f.suggestion.replace(/\n/g, " ")})_` : ""}`
      );
    }
  }
  header.push("", "_Generated by ABC PSA._");

  const inlineComments = result.findings
    .filter((f): f is CodeFinding & { line: number } => f.line !== null)
    .map((f) => ({
      path: f.file,
      line: f.line,
      body: `**[${f.severity}] ${f.dimension}**: ${f.message}${f.suggestion ? `\n\n_Fix: ${f.suggestion}_` : ""}`,
    }));

  return { summaryBody: header.join("\n"), event, inlineComments };
}

/** Format the review as a Markdown comment to post on the GitHub PR. */
export function buildReviewComment(result: CodeReviewResult, prNumber: number): string {
  const c = countsBySeverity(result.findings);
  const lines = [
    `### 🤖 ABC Code Review — PR #${prNumber}`,
    `**${result.verdict === "approve" ? "✅ Approve" : "🔧 Request changes"}** · Blocking ${c.blocking} · Suggestions ${c.suggestion} · Nitpicks ${c.nitpick}`,
    ``,
    result.summary,
  ];
  if (result.findings.length) {
    lines.push("");
    for (const f of result.findings) {
      const loc = `${f.file}${f.line ? `:${f.line}` : ""}`;
      lines.push(
        `- **[${f.severity}]** ${f.dimension} — \`${loc}\`: ${f.message.replace(/\n/g, " ")}${f.suggestion ? ` _(fix: ${f.suggestion.replace(/\n/g, " ")})_` : ""}`
      );
    }
  }
  lines.push("", "_Generated by ABC PSA._");
  return lines.join("\n");
}
